### ISSUE TITLE
Document GITHUB_TOKEN permissions required

### ISSUE THREAD

**Issue by BretFisher** [crazy-max/ghaction-container-scan#19]
After some testing, I believe this is true, but would like someone else to validate if possible before I update README.md

## GITHUB_TOKEN Minimum Permissions

If you want the scan to include the Dockerfile, you'll need to checkout the repository and give the job:

```yaml
permissions:
  contents: read
```

If you want to upload the SARIF report to GitHub Security, you'll need to add these permissions to the job:

```yaml
permissions:
  actions: read
  security-events: write
```

If you receive the error `Advanced Security must be enabled for this repository to use code scanning.` This likely means you're using a private repository and trying to upload SARIF reports, which requires a org admin to enable Advanced Security for the repository.

**Comment by crazy-max** [comment]
Yes you're right @BretFisher, feel free to open a PR thanks!
